export default [
  {
    id:1,
    theName:'SPM-1 Battleglove',
    place:'Hand',
    damage:'3d6',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:2,
    theName:'Scratchers',
    place:'Hand',
    damage:'1d6/3',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:3,
    theName:'Vampires',
    place:'Hand',
    damage:'1d6/3',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:4,
    theName:'Rippers',
    place:'Hand',
    damage:'1d6+3',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:5,
    theName:'Wolvers',
    place:'Hand',
    damage:'3d6',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:6,
    theName:'Big Knucks',
    place:'Hand',
    damage:'1d6+2',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:7,
    theName:'Hammer Hand',
    place:'Hand',
    damage:'1d10',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:8,
    theName:'Spike Hand',
    place:'Hand',
    damage:'1d6+3',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:9,
    theName:'Talon Foot',
    place:'Leg',
    damage:'1d6',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:10,
    theName:'Spike Heel Foot',
    place:'Leg',
    damage:'2d6',
    damageMultiplier:0,
    additionalArmor:0,
    newArmor:0,
    range:1
  },
  {
    id:11,
    theName:'Hydraulic Cilinders',
    place:'Leg',
    damage:'1d6',
    damageMultiplier:3,
    additionalArmor:0,
    newArmor:30,
    range:1
  },
  {
    id:12,
    theName:'Hydraulic Cilinders',
    place:'Hand',
    damage:'1d6/2',
    damageMultiplier:3,
    additionalArmor:0,
    newArmor:30,
    range:1
  },
  {
    id:13,
    theName:'Mio volokna',
    place:'Leg',
    damage:'1d6',
    damageMultiplier:2,
    additionalArmor:0,
    newArmor:25,
    range:1
  },
  {
    id:14,
    theName:'Myomar Strand',
    place:'Hand',
    damage:'1d6/2',
    damageMultiplier:2,
    additionalArmor:0,
    newArmor:25,
    range:1
  }
]