export default [
  {
    enDescription:"TargetImmobile",
    ruDescription:"ЦельНеподвижна",
    bonusValue:2
  },
  {
    enDescription:"TargetDodgingMelee",
    ruDescription:"ЦельУклоняетсяББ",
    bonusValue:-1
  },
  {
    enDescription:"MovingTargetREF10",
    ruDescription:"ДвижущаясяЦельРефл10",
    bonusValue:-3
  },
  {
    enDescription:"MovingTargetREF12",
    ruDescription:"ДвижущаясяЦельРефл12",
    bonusValue:-4
  },
  {
    enDescription:"MovingTargetREF14",
    ruDescription:"ДвижущаясяЦельРефл14",
    bonusValue:-5
  },
  {
    enDescription:"FastDraw",
    ruDescription:"НаВскидку",
    bonusValue:-3
  },
  {
    enDescription:"Ambush",
    ruDescription:"Засада",
    bonusValue:5
  },
  {
    enDescription:"AimedShotAtBody",
    ruDescription:"ПрицельныйВыстрелВтело",
    bonusValue:-4
  },
  {
    enDescription:"Ricochet",
    ruDescription:"Рикошет",
    bonusValue:-5
  },
  {
    enDescription:"BlindedLightDust",
    ruDescription:"Ослеплён",
    bonusValue:-3
  },
  {
    enDescription:"TargetSilhouet",
    ruDescription:"СилуэтЦели",
    bonusValue:2
  },
  {
    enDescription:"TurningFaceTarget",
    ruDescription:"ПоворачиваяЛицоКцели",
    bonusValue:-2
  },
  {
    enDescription:"UsingTwoWeapons",
    ruDescription:"сДвухРук",
    bonusValue:-3
  },
  {
    enDescription:"FiringWhileRunning",
    ruDescription:"СтреляяНабегу",
    bonusValue:-3
  },
  {
    enDescription:"FiringShoulderFromHip",
    ruDescription:"СтрельбаОтБедра",
    bonusValue:-2
  },
  {
    enDescription:"TurretMountedWeapon",
    ruDescription:"ТурельСкреплением",
    bonusValue:2
  },
  {
    enDescription:"VehicleMountedNoTurret",
    ruDescription:"ОружиеЗакрепленоНаТранспорте",
    bonusValue:-4
  },
  {
    enDescription:"LargeTarget",
    ruDescription:"БольшаяЦель",
    bonusValue:4
  },
  {
    enDescription:"SmallTarget",
    ruDescription:"МаленькаяЦель",
    bonusValue:-4
  },
  {
    enDescription:"TinyTarget",
    ruDescription:"КрошечнаяЦель",
    bonusValue:-6
  },
  {
    enDescription:"Aiming",
    ruDescription:"Прицелившись",
    bonusValue:1
  },
  {
    enDescription:"LaserSight",
    ruDescription:"ЛазерныйПрицел",
    bonusValue:1
  },
  {
    enDescription:"TelescopicSightExtreme",
    ruDescription:"ТелескопическийПрицелЭкстрДист",
    bonusValue:2
  },
  {
    enDescription:"TelescopicSightMedium",
    ruDescription:"ТелескопическийПрицелСредДист",
    bonusValue:1
  },
  {
    enDescription:"TargetingScope",
    ruDescription:"ПрицельныйВидоискатель",
    bonusValue:1
  },
  {
    enDescription:"Smartgun",
    ruDescription:"УмноеОружие",
    bonusValue:2
  },
  {
    enDescription:"SmartGoggles",
    ruDescription:"УмныеОчки",
    bonusValue:2
  },
  {
    enDescription:"ThreeRoundBurstCloseMedium",
    ruDescription:"ОчередьИзТрёхБлизкоСредне",
    bonusValue:3
  },
  {
    enDescription:"FullAutoClose",
    ruDescription:"ЗажавГашеткуБлизко",
    bonusValue:1
  },
  {
    enDescription:"FullAutoAllOther",
    ruDescription:"ЗажавГашеткуСреднеДалеко",
    bonusValue:-1
  }
]